include("node.jl")
include("edge.jl")
include("graph.jl")
include("queue.jl")
include("heuristics.jl")
include("prim.jl")
include("kruskal.jl")
include("creategraph.jl")
include("read_stsp.jl")
include("rsl.jl")
include("hk.jl")
include("graphplot.jl")
include("onetree.jl")

A=Node("a","A",nothing,Inf,0,0)
B=Node("b","B",nothing,Inf,0,0)
C=Node("c","C",nothing,Inf,0,0)
D=Node("d","D",nothing,Inf,0,0)

AB=Edge([A,B],1000)
AD=Edge([A,D],2)
AC=Edge([A,C],3)
BD=Edge([D,B],4)
BC=Edge([C,B],5)
CD=Edge([C,D],1000)

g=Graph("g",[A,B,C,D],[AB,AD,AC,BD,BC,CD])
show(g)
test=hk(g,10)
show(test)