include("graph.jl")
include("read_stsp.jl")

A=Node("A","a")
B=Node("B","b")
C=Node("C","c")
AB=Edge((A,B),1)
AC=Edge((A,C),2)
BC=Edge((B,C),3)
show(A)
show(B)
show(AB)

println("\nPartie graphe\n")
G=Graph("G",[A,B],[AB])
show(G)
add_node!(G,C)
add_edge!(G,AC)
add_edge!(G,BC)
show(G)

Title=read_header("bayg29.tsp")
#println(Title,"\n\n")
Edges=read_edges(Title,"bayg29.tsp")
println("\n\n",Edges)
Nodes=read_nodes(Title,"bayg29.tsp")
#println(Nodes)